# Static per-environment config — safe to commit.
# Dynamic config (org, accounts) lives in fetched.auto.tfvars.json,
# generated by: platform-bootstrap fetch --output terraform/envs/prod/fetched.auto.tfvars.json

aws_region  = "us-east-1"
project     = "platform"
environment = "prod"
