name: DevOps / Terraform Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "terraform/**"
      - ".tflint.hcl"
      - ".github/workflows/**"
  push:
    branches: [main, master]
    paths:
      - "terraform/**"
      - ".tflint.hcl"
      - ".github/workflows/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    permissions:
      contents: read
    uses: ffreis-org/ffreis-workflows-terraform/.github/workflows/tf-fmt.yml@105d9d036a68d89d47b6efe97d760849b99ec80b
    with:
      working-directory: "terraform"

  validate:
    permissions:
      contents: read
    uses: ffreis-org/ffreis-workflows-terraform/.github/workflows/tf-validate.yml@105d9d036a68d89d47b6efe97d760849b99ec80b
    needs: [fmt]
    with:
      chdir: "terraform/stack"
      validate-all-modules: true
      modules-dir: "terraform/modules"

  lint:
    permissions:
      contents: read
    uses: ffreis-org/ffreis-workflows-terraform/.github/workflows/tf-lint.yml@105d9d036a68d89d47b6efe97d760849b99ec80b
    needs: [fmt]
    with:
      lint-path: "terraform"
      tflint-config: ".tflint.hcl"

  trivy-config:
    permissions:
      contents: read
      security-events: write
      actions: read
    uses: ffreis-org/ffreis-workflows-terraform/.github/workflows/tf-security.yml@105d9d036a68d89d47b6efe97d760849b99ec80b
    needs: [fmt]
    with:
      scan-ref: "terraform"

  tfsec:
    permissions:
      contents: read
      security-events: write
      actions: read
    uses: ffreis-org/ffreis-workflows-terraform/.github/workflows/tf-tfsec.yml@105d9d036a68d89d47b6efe97d760849b99ec80b
    needs: [fmt]
    with:
      scan-path: "terraform"
      minimum-severity: "HIGH"
      soft-fail: false

  checkov:
    permissions:
      contents: read
      security-events: write
      actions: read
    uses: ffreis-org/ffreis-workflows-terraform/.github/workflows/tf-checkov.yml@105d9d036a68d89d47b6efe97d760849b99ec80b
    needs: [fmt]
    with:
      scan-directory: "terraform"
      framework: "terraform"
      soft-fail: false

  semgrep:
    permissions:
      contents: read
      security-events: write
      actions: read
    uses: ffreis-org/ffreis-workflows-terraform/.github/workflows/tf-semgrep.yml@105d9d036a68d89d47b6efe97d760849b99ec80b
    needs: [fmt]
    with:
      working-directory: "terraform"
      config: "p/terraform"
