name: Lefthook

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  push:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lefthook:
    permissions:
      contents: read
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-lefthook.yml@caa797cc7baec52e99f21b86f532a4b7c88cf4fa # fix/grype-install-outside-scan-path
    with:
      working-directory: "."
      go-version-file: "go.mod"
      install-govulncheck: true
      lefthook-bootstrap-command: "make lefthook-bootstrap"
      lefthook-bin: ".bin/lefthook"
